/**:
  ros__parameters:
    min_longitudinal_offset: -1.907
    max_longitudinal_offset: 1.907
    min_lateral_offset: -0.948
    max_lateral_offset: 0.948
    min_height_offset: -2.4
    max_height_offset: 0.036
